### ISSUE TITLE
Update on http://danesjenovdan.si/en/projects/

### ISSUE THREAD

**Issue by cylebrity** [danesjenovdan/danesjenovdan.si-en#1]
https://docs.google.com/spreadsheets/d/1V7kK9SyTRB4R1H8ZmVACcrwh5xrd_vEvOjfFb4FUYSE/edit#gid=1388812537

**Comment by LepkoQQ** [comment]
closed by 3d8e8e9d457274582069e39215f6df43b6ea9782
